### PR TITLE
Adding some optimizations, and including mock as dependency

### PR DESCRIPTION
**Pull request by eefret**
I found some minor optimizations, and added requirements.txt, also included mock in the dependency list as it was failing the tests because of this, feel free to check and merge if you feel is relevant :D

### CODE REVIEW

**Comment by arcturial** [comment]
I had to make some slight modifications in the latest commit, some changes in the pull request broke certain functionality. 

``` python
resp.text.encode('utf-8')
```

This still just returned a byte object, so I had to revert to setting the encoding before calling .text (seems to solve the problem)

Then I noticed that the Requests library handles array variables in GET slightly different, so I had to make modifications to the HTTP transport. It is not related to this pull request though, just part of the commit.

Thanks for the contribution.

**Comment by eefret** [comment]
Sorry, I ran the unittests and they passed so I thought everything was fine.

**Comment by arcturial** [comment]
My fault for not having coverage :P

I need to still add some tests that will mock the request methods and return fake responses, for now I added some basic ones to make sure the request method always returns a type 'str' as a response.

**Comment by eefret** [comment]
Sorry to bother u again, when will u upload to pip ?

**Comment by arcturial** [comment]
Will upload the latest changes in about an hour or so. The current version on pip should still be stable. Will tag the new one 0.1.1

**Comment by arcturial** [comment]
The new release should now be on pip.

**Comment by eefret** [comment]
Cool thanks chris

**Pull request merged**
